# These are supported funding model platforms

github: numbpill3d
patreon: 
open_collective: voidrane-splicer
ko_fi: numbpilled
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: neonmaxima
issuehunt: voidrane
lfx_crowdfunding: https://openprofile.dev/profile/voidrane
polar: # Replace with a single Polar username
buy_me_a_coffee: alicehortos
thanks_dev: numbpill3d
custom: 
